name = "precious"
version = "1.0.0"


description = "An implementation of the PRECIS framework for preparation, enforcement, and comparison of internationalized strings."
licences = ["MIT"]
repository = { type = "github", user = "NineFX", repo = "precious" }

# Supports the `dev` folder
gleam = ">= 1.11.0"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
iv = ">= 1.2.0 and < 2.0.0"
gleam_regexp = ">= 1.1.1 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
gleam_json = ">= 3.0.0 and < 4.0.0"
simplifile = ">= 2.2.1 and < 3.0.0"